### ISSUE TITLE
New release that includes bugfix?

### ISSUE THREAD

**Issue by tvestelind** [ergoserv/auxiliary_rails#49]
Hi!

I'm wondering if it would be possible to release a new version that includes the following PR https://github.com/ergoserv/auxiliary_rails/pull/48?

Thanks in advance!

**Comment by stgeneral** [comment]
Hi @tvestelind!

Sure, we are going to release the updated version, but not sure yet about the timeline.

Meanwhile, you can use the version from the `develop` branch, which already contains this fix, adding this line to your Gemfile:

```ruby
gem 'auxiliary_rails', git: 'https://github.com/ergoserv/auxiliary_rails', branch: 'develop'
```

Thank you for your interest in our gem!

**Comment by tvestelind** [comment]
Hi @stgeneral!

Thank you. I wanted to avoid a 'develop' dependency that I might forget :)

But it's no biggie, I'll wait for the next release. Thank you for creating this! :)
